### ISSUE TITLE
Remove dependency on `once_cell`

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#102]
Our test runner currently uses `once_cell::sync::Lazy` in a few places.  Discussion at https://github.com/NoahTheDuke/vim-just/pull/84#discussion_r1581661677 considered using `std::sync::LazyLock` instead of `once_cell`, but that didn't happen because `LazyLock` was nightly-only at the time.

[As of Rust 1.80.0, `LazyLock` is now stable.](https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html#lazycell-and-lazylock)

When CI gets Rust >= 1.80.0, should we switch to `LazyLock`?

**Comment by NoahTheDuke** [comment]
Seems right to me. Given that it's only us two building this thing, you can switch whenever you want.
