### ISSUE TITLE
Convert from new Sublime syntax

### ISSUE THREAD

**Issue by nk9** [NoahTheDuke/vim-just#21]
I wanted to alert you to the fact that [I've created a new syntax](https://github.com/nk9/just_sublime) for `just` using the Sublime syntax format. I have never written a syntax for Vim, so I'm not sure how directly applicable this is, but you may at least be able to apply some of the regexes.

In addition, I've added a [kitchen-sink](https://github.com/casey/just/blob/master/examples/kitchen-sink.just) justfile to the main `just` repo. There are probably other cases to cover, so further additions are welcome! The idea is to help stress test syntaxes.

**Comment by NoahTheDuke** [comment]
Cool, thanks for the heads-up! Vim's syntax system is really dumb, lol. It's got a lot of cool ideas but the syntax and rules are pretty byzantine. I don't think there's much we're missing at the moment, just indentation rules (which I don't know anything about). Was there any aspect you felt your highlighting does better than this? I can check it out.

Thanks for the kitchen-sink file, I'll add that to our test suite.

**Comment by nk9** [comment]
I haven't explored the vim, syntax, definition extensively, but I had a quick look at the file just now.

It may be missing some of the newer functions (eg `kebabcase`), and things like expressions (including parenthetical groups) in dependencies, assignments, and arguments. Also, I'm not sure if the syntax will properly deal with `if` statement chaining. Hopefully the kitchen-sink file will highlight some of these!

**Comment by NoahTheDuke** [comment]
Ah yeah, I haven't touched it much since I made it early last year so all of the new stuff isn't included. I'll use your as a reference!

**Comment by NoahTheDuke** [comment]
Sure!

**Comment by NoahTheDuke** [comment]
Yeah I'm really busy and don't use justfiles  much anymore. Want to be added to the repo?

**Comment by NoahTheDuke** [comment]
Invite has been sent! Thanks for helping out.

I tend to be conservative with changes but I'm not a fan of "semver" as I find it's a poor fit for anything not intended to be "infrastructure". You're basically free to do whatever you think is smart/reasonable to do. If you start poppin off, lmao, I can always remove access/revert/etc, so I'm not worried about that aspect.

I think the changes you proposed here are probably good/better; I did my best but ended up hardcoding a lot of silliness that I should have been more permissive about, and I am/was pretty inexperienced with vim syntax highlighting when I started the project.

I would prefer to keep the Rust test runner that I built, unless there's a "community standard" for such things. It's fast and Rust is nice.

**Comment by NoahTheDuke** [comment]
The way you update the tests is to run them and the copy-paste the output of the diff into the relevant files lol. They're effectively "snapshot" tests: at this stage of the syntax files, this is how they highlight the given file. And then any changes to the syntax file will have a corresponding change in the diff. It's a way to verify that a given word or line or syntax has the highlighting names you expect, without opening and closing vim over and over and over again.

I just pulled your branch, merged master (includes some test runner fixes), and ran it. It's annoying but should be easy enough to go through and copy-paste over the changes that look like you intended. If there's inconsistencies or issues, then you can change the syntax file and re-run to get better output.

**Comment by nk9** [comment]
> This was really helpful when working on the syntax file, thank you for making this!  @nk9 would it be OK with you if it's also added to the `vim-just` test suite?

Absolutely! Just please put a comment in mentioning the author and the original location it was copied from.

Really glad you found it useful. FYI, I've learned a bit more about the syntax while implementing the Sublime version, and there are more edge cases that aren't included in the kitchen sink file. Everything is covered in the test cases in the `just-sublime` repo, though. Has anybody located a utility to convert sublime syntax tests to something that can be used to verify vim syntaxes? If not, it shouldn't be THAT hard to write a converter …

**Comment by NoahTheDuke** [comment]
Pretty cool that sublime has syntax tests!
