### ISSUE TITLE
Tests fail to run

### ISSUE THREAD

**Issue by nk9** [NoahTheDuke/vim-just#23]
I get an error when I attempt to run the tests as described in the `README`:

```
vim-just/tests$ RUST_BACKTRACE=1 just run
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/tests`
test alias… thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:93:8
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1113:23
   4: tests::main
             at ./src/main.rs:86:23
   5: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: Recipe `run` failed on line 3 with exit code 101
```

**Comment by NoahTheDuke** [comment]
Just pushed a change, try it and let me know if it works now.

**Comment by nk9** [comment]
Thanks for looking! But unfortunately I get the same error. Is there any sort of cleaning I need to do beyond calling `just run` again? I'm on 3b8cd4b1d270108320bd0ffac939766e9cedf6b9.

**Comment by nk9** [comment]
I can confirm that the tests succeed once `colordiff` is installed. However, the error message says nothing about that utility. Also, I think the setup instructions are silent about it. So there's really no way for a casual user to avoid this problem or to discover how to fix it.

Should I file a new bug about this, or can we just use this one?

**Comment by NoahTheDuke** [comment]
The "Prerequisites" list `just` `colordiff` and `Rust`, and then have detailed install instructions for Rust as it's more complicated than a single binary.

Maybe the test runner could check for colorfiff and make a smarter error message.

**Comment by nk9** [comment]
Whoops! Right you are, sorry about that. I do think doing a check and failing more gracefully would be an improvement. Is that simple to achieve?

**Comment by NoahTheDuke** [comment]
Should be! We can check the output of `colordiff --version` and print something helpful.
