### ISSUE TITLE
Stop using `after/` directory

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#24]
Per `:help after-directory`, `after/` is intended for use on end-user systems "to overrule or add to the distributed defaults or system-wide settings".  Currently some of `vim-just`'s "distributed defaults" are set in files under `after/`.  We should move that code to the appropriate place(s) in the main part of `vim-just`.

**Comment by NoahTheDuke** [comment]
Oh that's interesting, I didn't know that.

**Comment by NoahTheDuke** [comment]
It means that vim will treat identifiers containing dashes as single "words" (vim text objects) instead of two words separated by a dash. Makes moving around justfiles feel more natural as the various vim keys treat words like `run-tests` as a unit.
