### ISSUE TITLE
Consider renaming `master` branch?

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#25]
The name `master` for git branches never really made sense to me.  And now it is [recommended to replace "master" with more technically precise alternatives wherever possible](https://inclusivenaming.org/word-lists/tier-1/_master/) (although that particular link is somewhat political, [their FAQ](https://inclusivenaming.org/faqs/) makes clear the initiative is about making terms clearer and more technically precise).

Naming our default branch `primary` would be way more descriptive of the development flow of this repo.

If we are going to rename the default branch, now would be a good time since the syntax files on `master` haven't been touched in years and a major update to this project is already in the works anyway.

Obviously this would need to be coordinated with all active maintainers.

To avoid breaking users' existing clones, we shouldn't do this completely abruptly.  One option would be:

1) Create a new branch `primary` at the current HEAD of `master`

2) Create a commit on `master` (and fast-forward merge it into `primary`) adding instructions to README.md for how to migrate an exsting clone from `master` to `primary`.  The instructions should work even if `master` gets deleted on the remote (I have been on the receiving end of such situation before, IIRC I was able to fix my local clone in-place and made partial notes how to do it).

3) Make `primary` the default branch, update our CI, and then merge `syntax-update` to `primary` when `syntax-update` is ready.  At this point `master` would become unmaintained (and disconnected from CI).

4) After a significant enough time window has passed, delete `master`.

Does this sound reasonable?

**Comment by NoahTheDuke** [comment]
I prefer `main` which I think is the new git default, but otherwise this is doable.

**Comment by NoahTheDuke** [comment]
@casey did some work back when I started, and this is upstreamed to vim-polyglot, but otherwise I don't think anyone else has done public work on it.

**Comment by NoahTheDuke** [comment]
I cannot make any plans to be online at a given time lol, but you should be able to make new branches in this repo and then I can change the default one we make sure nothing bad will happen.

**Comment by NoahTheDuke** [comment]
Done!

**Comment by NoahTheDuke** [comment]
Woah! That's wild. I don't use polyglot anymore due to size and general annoyance, but I'm still surprised to see it fall into disarray. Thanks for the research.

**Comment by NoahTheDuke** [comment]
I think that's a perfectly reasonable note.
