### ISSUE TITLE
Reconsider how we are instructing to install Rust

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#37]
Currently, the README link to the Rust prerequisite points to https://www.rust-lang.org/ and suggests installing Rust via `just install-rustup`.  Both of these are suboptimal, if not problematic:

1) That link is mostly general marketing-ish talk about the benefits of Rust and who uses it.  It does its purpose well, but it's not what we need here: we are writing for an audience who wants to install Rust as a prerequisite.  An installation instructions page, like we link to for `colordiff`, would be more suitable.

2) Regarding `just install-rustup`... let's not.  There is a reason the main Rust install page is so blatant where recommending `curl | sh`: this is generally a bad practice, unless A) the user is fully aware this will happen, and B) the user 100% trusts the URL.  The extra layer of a pre-provided justfile recipe takes away necessary advance warning.  We don't need to do this, as this recipe is not at all `vim-just`-specific.  Additionally, some dev environments require that installs like Rust be performed offline, so `rustup` is not always an option.

### Proposed solution:

For (1): change the Rust link in the README to https://forge.rust-lang.org/infra/other-installation-methods.html , which provides thorough installation instructions and covers all cases.
Even for those who want to use the "default", recommended `curl | sh` `rustup` based method of installing Rust, that page is still the best landing page, because it eases the reader in by calling it "the most straightforward, recommended way" while describing it in some more detail, objectively discussing pros and cons, and providing alternatives **right there**.  The main Rust installation page doesn't do this so well: it abruptly jumps into suggesting `curl | sh` with little explication, while kind of burying other installation methods.

For (2): remove the `just install-rustup` recipe.

If this is done after https://github.com/NoahTheDuke/vim-just/pull/34 is merged, it will be possible for people who want a `just install-rustup` recipe to add it to a custom local `justfile` outside of the repo and run it from cwd `tests/` same as before.  In the case of someone creating such recipe themselves, the concern is nonexistant because they know what they're putting in the recipe.

**Comment by NoahTheDuke** [comment]
I'm fine removing the `install-rustup` recipe, but I want to point people to the most recommended install instructions. If you want to include that link, that's chill, but it should be secondary: "To install rust, [follow the instructions](https://www.rust-lang.org/tools/install)] on the Rust website. (Other methods are documented [here](https://forge.rust-lang.org/infra/other-installation-methods.html).)"

**Comment by NoahTheDuke** [comment]
That works for me.
