### ISSUE TITLE
Is there a "too soon" to add new `just` syntaxes?

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#40]
In the last few days I've been keeping an eye on this - https://github.com/casey/just/commit/bba673fd791fa08aac95cf263141a4c69162681b

But not sure whether adding it to `vim-just` already would be premature?  On the one hand, it's valid, working syntax, it doesn't require `--unstable` to use, and it would be easy to add here.  On the other hand, currently it's only in pre-release version of `just` and not yet documented.

Should we add `env()` to `vim-just` as soon as one of us finds the time to do that + write tests?  Or rather wait for it to be documented at https://just.systems/man/en/ before considering adding it here?

As the issue title implies, this isn't only asking about `env()`, but more generally if there is a "too soon" to add new `just` syntaxes - idk if a non-`--unstable` `just` syntax not being documented has any implication beyond simply "no one has added it to documentation yet".

**Comment by NoahTheDuke** [comment]
In the past I would update when a new release was cut. Most users aren't working from main, so this felt safest.

**Comment by NoahTheDuke** [comment]
Hope things get better soon for you. Thanks for keeping up with this.
