### ISSUE TITLE
Delete mangled dangling commit?

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#41]
After pushing latest set of fixes, I was surprised to discover that Github had transformed my referencing a cluster name in a commit message into a mention of another user.  So I quickly force pushed to correct it.

But the old commit is still accessible?

Hope this didn't send that user an unintended notification :fearful: It would be best to delete that commit.

If this were a local repo, [this command](https://stackoverflow.com/a/14728706) would do the job.  But not finding how to trigger Github to run such command on the remote?

@NoahTheDuke as repo owner do you have a way to do this?

Sorry everyone for the trouble :frowning_face:

**Comment by NoahTheDuke** [comment]
Nothing to do about it, but i think you're okay.
