### ISSUE TITLE
Test runner cleanup on SIGINT

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#45]
Sometimes it is useful to terminate the test runner with Ctrl+C/SIGINT, e.g. if it seems super slow & want to check if the cause is some change introducing an invalid regex.  Currently this leaves behind the temporary files in `/tmp` and the `.vim` symlink.  Would it be possible to make the test runner perform cleanup on Ctrl+C/SIGINT-initiated termination?

**Comment by NoahTheDuke** [comment]
That's probably a good idea. I don't know enough about how Rust handles that to make any suggestions but you're welcome to look into it and make any changes you feel helpful or necessary.
