### ISSUE TITLE
Investigate alternative syncing methods

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#46]
Regarding

https://github.com/NoahTheDuke/vim-just/blob/2a94aecd8eb53e1147392da33df8ee4ea6e482d6/syntax/just.vim#L12

It seems there may not be a good number for `minlines` here.  Despite multiple attempts to fine-tune this value, I still keep running into cases where jumping around in a justfile results in incorrect highlighting that requires scrolling to fix.

One example where the current value reliably fails: delete lines at the end of our repo root justfile until the last line of `optrx` is the very last line of the justfile, then reopen it in a Vim/GVim that's ~24-26 lines tall and jump to the very end with `Ctrl+End`.  All of the visible text is part of the recipe body, but it's highlighted as if it were part of a preceding triple-quoted string, until scrolling up beyond it all and back down.

Per `:help syn-sync`, there are other non-default methods of syntax syncing -

```
There are four ways to synchronize:
1. Always parse from the start of the file.
   |:syn-sync-first|
2. Based on C-style comments.  Vim understands how C-comments work and can
   figure out if the current line starts inside or outside a comment.
   |:syn-sync-second|
3. Jumping back a certain number of lines and start parsing there.
   |:syn-sync-third|
4. Searching backwards in the text for a pattern to sync on.
   |:syn-sync-fourth|
```

(2) is not applicable to justfiles.  (1) [was already rejected](https://github.com/NoahTheDuke/vim-just/commit/87bc49da76a6867127ca0abd84d77b8ed4f33311).

(4) looks like it might be interesting in theory, but unfortunately I'm unable to get my head around it enough to come up with something to try :frowning: 

Is it possible to do better than purely `minlines`-based syncing?

**Comment by NoahTheDuke** [comment]
I'm fine with `fromstart` if you wanna experiment with it, I think I changed it because in other syntaxes it can slow down when the file is big (like the 6k line file in one of my other projects). How big are people making their justfiles lol?

We can always change it back, so there's no big pressure here.
