### ISSUE TITLE
repo settings: disable unused features

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#57]
Saw in another project a suggestion to disable unused Github repo features, with links to https://github.com/MarkedDown/Disable for instructions.  This sounds a good idea, @NoahTheDuke could you please do this for `vim-just`?

In our case, the features to disable would be:
- [x] Packages
- [x] Projects
- [x] Wiki (not only for [these reasons](https://github.com/MarkedDown/Wiki), but also I have seen some nasty insidious abuse of wikis)

Thanks :slightly_smiling_face:

**Comment by NoahTheDuke** [comment]
Sure, that seems fine by me.
