### ISSUE TITLE
Tests justfile lint should not run formatting check if Clippy emits warnings

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#62]
Our tests justfile currently contains this recipe:

https://github.com/NoahTheDuke/vim-just/blob/90e299ec91fa8ff88f73150f824f77f86b0f867e/tests/justfile#L28-L31

If that `cargo clippy` command emits warnings, it still exits with status 0, so the recipe will go on to the formatting check.  This is bad because if the formatting is wrong enough that the formatting check shows a lot of output, it can obscure that there were clippy warnings.

One way to fix this is to append `-- -Dwarnings` to the clippy command.  While this would be better than the current state, it's not a great solution: this also makes warnings printed as errors and with me not being an experienced Rustacean, seeing "error" for warnings is confusing.

Is there an alternative way to do this that keeps warnings printed as warnings?

**Comment by NoahTheDuke** [comment]
That looks great, better than I would have written. Thanks for looking into that.
