### ISSUE TITLE
Remove `justBuiltInFunctionsError`?

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#67]
While trying to fix an issue that may affect performance and how we highlight functions, noticed that one of our most performance-expensive matches is this -

https://github.com/NoahTheDuke/vim-just/blob/61effac68ca42dbe515d488c4fef73035ce4f281/syntax/just.vim#L226-L228

Not sure this is worth the overhead.  It would seem unusual for someone to accidentally make this error, wouldn't it?  As a test, removing these measurably speeds up Vim total execution time on our test suite (~0.1-0.15 seconds on my machine).

Should we remove this error match?

**Comment by NoahTheDuke** [comment]
I've wondered about this. Maybe regex to match the built ins isn't worth it. Instead we could just match anything in function position and let a linter or lsp or running it inform the user about an error.

**Comment by NoahTheDuke** [comment]
Ah yeah, that's a good point. Try it out! I bet it would simplify some things.
