### ISSUE TITLE
`serde_yaml` is officially dead

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#81]
Our ftdetect test runner currently uses `serde_yaml` for deserializing the test cases specifications.  But this crate [is now officially dead](https://github.com/dtolnay/serde-yaml/releases/tag/0.9.34), with [last version ending in "+deprecated"](https://crates.io/crates/serde_yaml).

The `unsafe-libyaml` crate (by the same author) that `serde_yaml` depends on, also appears no longer maintained.

I'm looking into possible replacements as I get the chance.

**Comment by NoahTheDuke** [comment]
I don't know that we need to change anything until our code starts breaking.
