### ISSUE TITLE
`:TOhtml` will be subject to breaking changes

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#86]
As part of looking into https://github.com/NoahTheDuke/vim-just/issues/85 I ran our syntax highlighting tests against the latest Neovim development pre-release (`NVIM v0.10.0-dev-2849+g4946489e2`).  It went badly:

1) The strings our test runner expects in the HTML were not present, so it panicked.

2) After fixing (1), 100% of our test cases failed.  This appears to be due to changes in `:TOhtml`:
- Some internal groups, particularly ones intentionally not linked to any highlighting type (such as `justRecipeParenDefault` and `justShellSetValue`),  are now appearing in the html.  These are implementation details that should not be required to match to pass the tests.
- Tabs are being converted to spaces.  The integrity of the tests requires keeping tabs as tabs and spaces as spaces.
- Trailing newline handling has changed.

That's only what I noticed, might have missed other differences.

Not sure we need to do anything at this stage, since this is pre-release and our tests pass with latest Neovim release 0.9.5, but thought this should be noted.

**Comment by NoahTheDuke** [comment]
Holy shit. That's great news. Please post whatever you write so I can learn from it, I'm very poor at vimscript. (Maybe it could even be in lua and be faster still.)

**Comment by NoahTheDuke** [comment]
This is sick, dude, thank you for taking care of all this.
