### ISSUE TITLE
ftdetect tests fail in Neovim 0.10

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#89]
<details>

```
$ nvim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
$ TEST_VIM=nvim just ftdetect
cargo run --bin=test-ftdetect
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/test-ftdetect`
TEST FAILED: FtdetectCase { filename: None, content: Some("#!//usr/local/bin/just -f\n"), not_justfile: true } (file /tmp/.tmppbSGHk/s8F79): unexpectedly detected as 'just'
TEST FAILED: FtdetectCase { filename: None, content: Some("#!/usr/bin/just"), not_justfile: true } (file /tmp/.tmppbSGHk/xVKsDhwT): unexpectedly detected as 'just'
TEST FAILED: FtdetectCase { filename: None, content: Some("#!/usr/bin/just\n"), not_justfile: true } (file /tmp/.tmppbSGHk/a): unexpectedly detected as 'just'
TEST FAILED: FtdetectCase { filename: None, content: Some("#!/usr//bin/env just -f\n"), not_justfile: true } (file /tmp/.tmppbSGHk/DsNnawsInkLm): unexpectedly detected as 'just'
Error: Custom { kind: Other, error: "4/31 tests failed." }
error: Recipe `ftdetect` failed on line 31 with exit code 1
```
</details>

These failures don't occur in Neovim <= 0.9.5 or in Vim.

It's not a bug in the test runner.  Neovim 0.10.0 really does detect these as justfiles.

Turns out shebangs with repeated slashes like `#!/usr//bin/just -f` actually do work (at least on Xubuntu 22.04), so 2 of these 4 test cases are wrong.  But the shebangs invoking `just` without flags are not correct `just` script shebangs and should not result in detection as justfile.

**Comment by NoahTheDuke** [comment]
Hmmmmmm that's very strange! I'm not sure why it being added upstream would change our behavior.

**Comment by NoahTheDuke** [comment]
Given that this can be different depending on platform and you can set command line arguments (`--working-directory .` as in that chapter), it might be worthwhile to be permissive here.
